server:
  port: 8761

spring:
  profiles:
    active: local
    group:
      local:
        - console-logging
      test:
        - console-logging
      prod:
        - console-logging
        - file-logging
  application:
    name: spring-cloud-eureka

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false