server:
  port: 8761

spring:
  application:
    name: cground-spring-cloud-eureka

eureka:
  client:
    register-with-eureka: false   # euraka? registry? ???? ??? ??, ??? ???
    fetch-registry: false         # registy? ?? ??? ???? ??? ??